#.travis.yml

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install
  - npm install -g serverless
  - pip install --user awscli
  - ./retrieve-keys.sh

script:
  - echo 'No testing currently'

after_success:
  - sls deploy

notifications:
  email:
    on_failure: kylec32@gmail.com
    on_success: kylec32@gmail.com
