service:
  name: wishListSharer

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 10
  region: us-west-2
  memorySize: 256
  environment: 
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    IOPIPE_TRACE_AUTO_HTTP_ENABLED: true
    CAPTCHA_SECRET: ${env:CAPTCHA_SECRET}
    MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
    #AWS_REGION: ${opt:region, 'us-west-2'}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "dynamodb:Scan"
         - "dynamodb:PutItem"
         - "dynamodb:UpdateItem"
         - "dynamodb:GetItem"
         - "dynamodb:DescribeStream"
         - "dynamodb:GetRecords"
         - "dynamodb:GetShardIterator"
         - "dynamodb:ListStreams"
       Resource:
        - Fn::GetAtt:
          - eventsTable
          - Arn
        - Fn::GetAtt:
          - userTable
          - Arn
    -  Effect: "Allow"
       Action:
         - "SNS:Publish"
       Resource:
        Fn::Join:
          - ""
          - - "arn:aws:sns:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":eventsTopic"


functions:
  authorizer:
    handler: handlers/user-management.authorizer
  presistEvent:
    handler: handlers/eventHandler.persistEvent
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":eventsTopic"
          topicName: eventsTopic
  signUp:
    handler: handlers/user-management.signUp
    events:
      - http:
          method: post
          path: sign-up
          cors: true
  handleSignUpEmail:
    handler: handlers/email-handler.handleNewUser
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  signIn:
    handler: handlers/user-management.signIn
    events:
      - http:
          method: post
          path: sign-in
          cors: true
  forgottenPassword:
    handler: handlers/user-management.forgottenPassword
    events:
      - http:
          method: post
          path: reset/{email}
          cors: true
          request:
            parameters:
              paths:
                email: true
  handleForgottenPassword:
    handler: handlers/email-handler.handleForgottenPassword
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  resetPassword:
    handler: handlers/user-management.resetPassword
    events:
      - http:
          method: post
          path: /reset
          cors: true
  handleResetPassword:
    handler: handlers/user-management.handleResetPassword
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  followNew:
    handler: handlers/connectionHandler.addNew
    events:
      - http:
          method: post
          path: /connections/{identifier}
          request:
            parameters:
              paths:
                identifier: true
          cors: true
          authorizer: authorizer
  handleConnectUsers:
    handler: handlers/connectionHandler.handleConnectUsers
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  eventProcess:
    handler: services/EventProcessor.verify
    events:
      - http:
          method: post
          path: /event-processor
          cors: true
  getFollowers:
    handler: handlers/connectionHandler.getConnections
    events:
      - http:
          method: get
          path: /connections
          cors: true
          authorizer: authorizer
  searchUsers:
    handler: handlers/user-management.searchUsers
    events:
      - http:
          method: get
          path: /users/{name}
          cors: true
          authorizer: authorizer
  deleteConnection:
    handler: handlers/connectionHandler.deleteConnection
    events:
      - http:
          method: delete
          path: /connections/{identifier}
          request:
            parameters:
              paths:
                identifier: true
          cors: true
          authorizer: authorizer
  handleDisconnectUser:
    handler: handlers/connectionHandler.handleDisconnectUser
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  verify:
    handler: handlers/user-management.verify
    events:
      - http:
          method: post
          path: verify
  handleSignUpEvent:
    handler: handlers/user-management.handleSignUpEvent
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  addPresent:
    handler: handlers/presentHandler.addNew
    events:
      - http:
          method: post
          path: /my/presents
          cors: true
          authorizer: authorizer
  handlePresentNotifications:
    handler: handlers/presentHandler.handlePresentNotifications
    timeout: 30
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  handleAddPresent:
    handler: handlers/presentHandler.handleAddNew
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  getUserPresents:
    handler: handlers/presentHandler.getUserPresents
    events:
      - http:
          method: get
          path: /my/presents
          cors: true
          authorizer: authorizer
  updatePresent:
    handler: handlers/presentHandler.update
    events:
      - http:
          method: put
          path: /my/presents/{presentId}
          request:
            parameters:
              paths:
                presentId: true
          cors: true
          authorizer: authorizer
  handleUpdatePresent:
    handler: handlers/presentHandler.handleUpdate
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  deletePresent:
    handler: handlers/presentHandler.deletePresent
    events:
      - http:
          method: delete
          path: /my/presents/{presentId}
          request:
            parameters:
              paths:
                presentId: true
          cors: true
          authorizer: authorizer
  markPresentAsPurchased:
    handler: handlers/presentHandler.markAsPurchased
    events:
      - http:
          method: put
          path: /presents/{userId}/{presentId}/purchased
          request:
            parameters:
              paths:
                userId: true
                presentId: true
          cors: true
          authorizer: authorizer
  handleMarkPresentAsPurchased:
    handler: handlers/presentHandler.handleMarkAsPurchased
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  unmarkPresentAsPurchased:
    handler: handlers/presentHandler.unmarkAsPurchased
    events:
      - http:
          method: delete
          path: /presents/{userId}/{presentId}/purchased
          request:
            parameters:
              paths:
                userId: true
                presentId: true
          cors: true
          authorizer: authorizer
  handleUnmarkPresentAsPurchased:
    handler: handlers/presentHandler.handleUnmarkAsPurchased
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  handleDeletePresent:
    handler: handlers/presentHandler.handleDeletePresent
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - eventsTable
              - StreamArn
  getFollowedPresents:
    handler: handlers/followedPresentHandler.getPresents
    events:
      - http:
          method: get
          path: /presents
          cors: true
          authorizer: authorizer


custom:
  stage: "${opt:stage, self:provider.stage}"

resources:  # CloudFormation template syntax
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:custom.stage}
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,PUT,POST,DELETE'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eventsTable
        AttributeDefinitions:
          - AttributeName: event_id
            AttributeType: N
        KeySchema:
          - AttributeName: event_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 15
          WriteCapacityUnits: 15
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable
        AttributeDefinitions:
          - AttributeName: user_name
            AttributeType: S
        KeySchema:
          - AttributeName: user_name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
    eventTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "eventsTopic"
